### ISSUE TITLE
New Trilinos Package Checklist

### ISSUE THREAD

**Issue by jmgate** [SNLComputation/compadre#165]
Part of #164.

@kuberry, we'll need to fill out the following checklist in order to submit Compadre as a new package to Trilinos.  I've filled in what I can, but I'd prefer if you'd fill in more specifics where appropriate.

1. What is the proposed package's name?
   *  Compadre
1. What is the purpose for the package?
   *  Compadre is designed to set-up, solve, and apply the solution of small, independent quadratic programs formulated via Generalized Moving Least Squares (GMLS). By specifying a linear sampling functional, a scalar/vector space, and a target operation, Compadre will use information from a k-d tree nearest neighbor search to evaluate the action of the sampling functional on the scalar/vector space at neighbor sites. The product of matrices are inverted and the solution to the linear system stored. Additional features allow for parallel application of the solution to the data.
1. Why should this functionality not be included in an existing Trilinos package?
   *  Compadre provides a non-parametric regression technique for reconstruction functions from data, as well as the evaluation of meshless shape functions. It can be thought of as a meshless discretization package similar in nature to Intrepid.
1. The TriBITS build system supports easy build-time incorporation of Trilinos-compatible packages. This might be an appropriate alternative to official inclusion into Trilinos. On the other hand, if the candidate package can provide basic capabilities that might be used by existing or future Trilinos packages, inclusion in Trilinos might be best. Why should the proposed new package be added to the Trilinos repository, rather than being a Trilinos-compatible, stand-alone package that is included in the Trilinos build through an external repository?
   *  You can think of Compadre along the lines of Shards/Intrepid.  It could be useful for other/future Trilinos packages as a way to evaluate meshless shape functions as well as a point cloud data regression technique which would be useful for coupling multiple codes together.
1. What required and optional internal Trilinos packages dependencies will this code have?
   *  Required:  Kokkos.
1. What required and optional external TPL dependencies will this code have?
   *  Required:  LAPACK+BLAS or MKL (if on CPU) or CUDA+CUBLAS+CUSOLVER (if on GPU).
   *  Optional:  MPI.
1. Will this be immediately considered Stable code or Experimental Code?
   *  Experimental.
1. Describe the subpackages the new package will contain, if applicable.
   *  Not applicable.
1. What is the long term development, support, and maintenance plan for the new package going to be?
   *  Software currently supported by CANGA project (2 years) as well as by ESRF LDRD (1 year).
1. Who is going to maintain this package? If no-one can pledge long term support for the package, then when the package is released it should be made clear that the Trilinos community will not be providing long term support for the package.
   *  @kuberry, @pbosler, @quang-ha

**Comment by jmgate** [comment]
@kuberry, can you give me a list of the Compadre developers?

**Comment by kuberry** [comment]
Former developers as well or just current ones?

**Comment by jmgate** [comment]
Just current ones.

**Comment by kuberry** [comment]
Me and Quang-Thinh Ha, currently.
