### ISSUE TITLE
Create TriBITS Build Alongside Raw CMake Build

### ISSUE THREAD

**Issue by jmgate** [SNLComputation/compadre#171]
Part of #164.

# What Needs to Be Done?
We are unable to get Compadre into Trilinos without first getting it building via TriBITS.  One way to do this involves [inserting a TriBITS build system alongside the raw CMake build system](https://tribits.org/doc/TribitsDevelopersGuide.html#how-to-put-a-tribits-and-raw-cmake-build-system-side-by-side) that already exists in Compadre.  This includes the following steps:
- [x] Insert the `include_tribits_build` macro into the root `CMakeLists.txt` file.
- [x] Modify the root `CMakeLists.txt` file to include the following logic:
   ```cmake
   if (${PROJECT_NAME}_TRIBITS_DIR)
     # Insert magic for TriBITS build.
   else()
     # Insert raw CMake build.
   endif()
   ```
- [x] Insert `include_tribits_build()` as the first line of all other `CMakeLists.txt` files.
- [x] Create `CMakeLists.tribits.cmake` files as siblings to all other `CMakeLists.txt` files, and insert the necessary TriBITS magic to do the equivalent to what's in the sibling file.
- [x] Make sure everything builds both ways.

**Comment by jmgate** [comment]
@bartlettroscoe, Compadre includes a header-only TPL that's snapshotted into its source in `src/tpl/nanoflann.hpp`.  How do I include that sucker in the TriBITS build?  It doesn't look like including it in `TRIBITS_REPOSITORY_DEFINE_TPLS()` is the right thing to do.  Does something still belong in `TPLsList.cmake` though?  Alternatively, should I just treat it as one of the package's header files instead of as a TPL?

**Comment by bartlettroscoe** [comment]
> Compadre includes a header-only TPL that's snapshotted into its source in src/tpl/nanoflann.hpp

@jmgate, For now, to make your life easy, just treat as regular header files that belong to the Compadre package.

NOTE: In general it is ill advised to unconditionally build an external TPL in a your package since it cases causes integration problems down the line.  See the [M12 "For external dependencies, allow installing, building, and linking against an outside copy of external software]( https://github.com/xsdk-project/xsdk-community-policies/blob/master/package_policies/M12.md) in the document:

* https://github.com/xsdk-project/xsdk-community-policies

In the near future, TriBITS will support building this as an either internal package or point to an external pre-installed package (i.e. TPL).  This is what the work in TriBITSPub/TriBITS#63 and TriBITSPub/TriBITS#299 will allow (which I am supposed to be working on right now instead of ATDM :-( ).  That will satisfy that policy M12.

**Comment by jmgate** [comment]
Hey @kuberry, is your `examples` directory really examples, or is it tests?  If both, any chance we could subdivide it such that theres an `examples` directory along with a `tests` one?

**Comment by kuberry** [comment]
Hi @jmgate, it is both the executables for the tests as well as the test. The test adding could be done in a tests folder. So yes, they can be divided.

**Comment by jmgate** [comment]
Do the executables for the tests get run on their own as examples, or are they just there for the sake of the tests?

**Comment by kuberry** [comment]
Both. They both demonstrate the ability to solve many different PDEs and also they exercise portions of the code base. We don't have any 'gold-file' type tests. Most tests either get the exact solution using a polynomial manufactured solution or perform a convergence study and check the rates.

**Comment by jmgate** [comment]
Once #173 is merged, we're ready to finish out this work with the following tasks:
* [ ] Create a branch off of `develop` in Trilinos.
* [ ] Add Compadre to the list of packages with
   ```diff
   diff --git a/PackagesList.cmake b/PackagesList.cmake
   index 5c541a2..3801b0c 100644
   --- a/PackagesList.cmake
   +++ b/PackagesList.cmake
   @@ -64,6 +64,7 @@ TRIBITS_REPOSITORY_DEFINE_PACKAGES(
      Kokkos                packages/kokkos                   PT
      Teuchos               packages/teuchos                  PT
      KokkosKernels         packages/kokkos-kernels           PT
   +  Compadre              packages/compadre                 EX
      RTOp                  packages/rtop                     PT
      Sacado                packages/sacado                   PT
      MiniTensor            packages/minitensor               PT
   ```
* [ ] Snapshot Compadre into Trilinos.
* [ ] Push the branch.
* [ ] Create a PR in Trilinos.
* [ ] Wait for testing to pass, reviews, etc.
* [ ] Merge the PR.
