### ISSUE TITLE
Create Script to Snapshot Compadre into Trilinos

### ISSUE THREAD

**Issue by jmgate** [SNLComputation/compadre#175]
Part of #164.

The preferred way of snapshotting a package into Trilinos is via the `snapshot-dir.py` tool from TriBITS.  That script uses rsync to do a complete copy of the source directory into the destination directory.  That's not exactly what we want for Compadre because we want to be able to exclude certain files/directories (e.g., `kokkos`, `python`) from the snapshot.  As such, we'll need to write our own script to do the snapshotting, but it can leverage the `snapshot-dir.py` script under the hood.

**Comment by jmgate** [comment]
Note that I'll be pausing work on #171 to work on this issue, because this will be easier to do when working remotely.  That said, I expect to get back to #171 soon, likely well before we're allowed to return to work.

**Comment by jmgate** [comment]
@kuberry, what version(s) of Python do you support?

**Comment by jmgate** [comment]
Hopefully the majority of this work will actually take place in [TriBITS#307](https://github.com/TriBITSPub/TriBITS/issues/307).

**Comment by kuberry** [comment]
@jmgate For running certain tests in ctests, Python 3.x will work (>=3.4.0).

**Comment by kuberry** [comment]
I think most everything would work in Python 2.7.x, except for "print variable" vs "print(variable)".

**Comment by jmgate** [comment]
I think the work in [TriBITS#307](https://github.com/TriBITSPub/TriBITS/issues/307) is complete, but we'll have to wait for that to be merged and then for TriBITS to be snapshotted into Trilinos.  In the meantime, I can start on the script in compadre that will wrap `snapshot-dir.py`.
