### ISSUE TITLE
basis dir not included in install target

### ISSUE THREAD

**Issue by pbosler** [SNLComputation/compadre#198]
The `src/basis` folder is not copied to the installed `include` directory. Instead, its contents are copied, so the line `#include "basis/Compadre_ScalarTaylorPolynomials.hpp"` fails when I link against the installed Compadre target.

**Comment by pbosler** [comment]
Based on yesterday's discussion, I"m now building with Trilinos and I have the same kind of build vs install structure mismatch, this time with the `tpl/` folder instead of the `basis/` folder.   They're installed in a flat structure, but the `#include "tpl/nanoflann.hpp"` fails because there is no `tpl/`.

**Comment by kuberry** [comment]
Hi @pbosler, these changes are only in the master branch of this repo, not yet in Trilinos.

**Comment by pbosler** [comment]
Ok, I'll cherry pick the commits here for the time being, then pull trilinos/develop (?) later?

**Comment by kuberry** [comment]
I'll drop the link to the status getting this fix snapshotted into Trilinos here: https://github.com/trilinos/Trilinos/pull/7439

**Comment by kuberry** [comment]
Fix is now in this repo and in Trilinos snapshot.
