### ISSUE TITLE
Trilinos/CUDA build CMake variables not set

### ISSUE THREAD

**Issue by pbosler** [SNLComputation/compadre#216]
I'm not sure whether or not this issue belongs here or in Trilinos...

Something isn't working with the compadre package's CMake install target for Cuda builds --- the Compadre library is not included in the CMake `Trilinos_LIBRARIES` variable.

Verify the library exists:

```
~/trilinos-cuda/install/lib$ ls
cmake                  libkokkoscore.a     libteuchoskokkoscomm.a     libteuchosparser.a     libtpetraclassiclinalg.a   libxpetra.a
libcompadre.a          libkokkoskernels.a  libteuchoskokkoscompat.a   libteuchosremainder.a  libtpetraclassicnodeapi.a  libxpetra-sup.a
libkokkosalgorithms.a  libteuchoscomm.a    libteuchosnumerics.a       libtpetra.a            libtpetraext.a             libzoltan2.a
libkokkoscontainers.a  libteuchoscore.a    libteuchosparameterlist.a  libtpetraclassic.a     libtpetrainout.a           libzoltan.a
```

In project that links to Trilinos `<project_root>/CMakeLists.txt`
```
FIND_PACKAGE(Trilinos REQUIRED HINTS ${Trilinos_ROOT})
if (Trilinos_FOUND)
  message("Trilinos found. Details:")
  printvar(Trilinos_INCLUDE_DIRS)
  printvar(Trilinos_LIBRARIES)
  printvar(Trilinos_TPL_INCLUDE_DIRS)
  printvar(Trilinos_TPL_LIBRARIES)
endif()
```
CMake output shows that `Trilinos_LIBRARIES` does not include `libcompadre.a`: 

```
Trilinos found. Details:
Trilinos_INCLUDE_DIRS: /ascldap/users/pabosle/trilinos-cuda/install/include
Trilinos_LIBRARIES: zoltan2;xpetra-sup;xpetra;tpetraext;tpetrainout;tpetra;tpetraclassiclinalg;tpetraclassicnodeapi;tpetraclassic;zoltan;kokkoskernels;teuchoskokkoscomm;teuchoskokkoscompat;teuchosremainder;teuchosnumerics;teuchoscomm;teuchosparameterlist;teuchosparser;teuchoscore;kokkosalgorithms;kokkoscontainers;kokkoscore
```

Double check: Try the same thing with Trilinos/OpenMP, and Compadre is there (it's the first one):

```
Trilinos found. Details:
Trilinos_INCLUDE_DIRS: /ascldap/users/pabosle/trilinos-openmp-debug/install/include
Trilinos_LIBRARIES: compadre;zoltan2;xpetra-sup;xpetra;tpetraext;tpetrainout;tpetra;tpetraclassiclinalg;tpetraclassicnodeapi;tpetraclassic;zoltan;kokkoskernels;teuchoskokkoscomm;teuchoskokkoscompat;teuchosremainder;teuchosnumerics;teuchoscomm;teuchosparameterlist;teuchosparser;teuchoscore;kokkosalgorithms;kokkoscontainers;kokkoscore
```

**Comment by kuberry** [comment]
Hi @pbosler. Thanks for reporting this and for the level of detail. This should really help narrowing down where the issue is. I'll check things in the CMakeLists.txt, but this does look more like a Trilinos issue to me (which I'll make sure gets to the right place, if true).

**Comment by kuberry** [comment]
In compadre, we don't add our package to Trilinos_LIBRARIES ourselves. It is handled in Trilinos.
In Trilinos, there are two options currently set for Compadre:

PackagesList.cmake:112:  Compadre              packages/compadre                 ST
PackagesList.cmake:194:TRIBITS_DISABLE_PACKAGE_ON_PLATFORMS(Compadre Windows)

Would you mind trying to delete line 194 (it shouldn't help, but perhaps this is disabling more than ST->EX on Windows)?

If that doesn't help, would you mind setting ST->PT and see if that fixes the issue?

I don't know enough about the Trilinos packaging to chase this much further there, so I think we should check these two things then pass it along to Ross.

**Comment by pbosler** [comment]
Moving `-DTrilinos_ENABLE_Compadre=ON` higher in my Trilinos configure script fixed the issue:

```
-DTrilinos_ENABLE_ALL_PACKAGES:BOOL=OFF \
-DTrilinos_ENABLE_ALL_OPTIONAL_PACKAGES:BOOL=OFF \
\
-DTrilinos_ENABLE_Teuchos:BOOL=ON \
-DTeuchos_KOKKOS_PROFILING=ON \
\
-DTrilinos_ENABLE_Compadre:BOOL=ON \ # Moved Compadre switch to here
\
-DTrilinos_ENABLE_Kokkos:BOOL=ON \
-DTrilinos_ENABLE_KokkosCore:BOOL=ON \
-DTrilinos_ENABLE_KokkosAlgorithms:BOOL=ON \
-DTrilinos_ENABLE_KokkosKernels:BOOL=ON \
-DKokkos_ENABLE_SERIAL:BOOL=ON \
-DKokkos_ENABLE_OPENMP:BOOL=OFF \
-DKokkos_ENABLE_PTHREAD:BOOL=OFF \
-DKokkos_ENABLE_CUDA:BOOL=ON \
-DKokkos_ARCH_MAXWELL52=ON \
-DKokkos_ENABLE_PROFILING=ON \
-DKokkos_ENABLE_CUDA_UVM:BOOL=ON \
\
-DTrilinos_ENABLE_Zoltan2:BOOL=ON \
-DTpetra_INST_SERIAL:BOOL=ON \
-DTpetra_ENABLE_DEPRECATED_CODE:BOOL=OFF\
\
#-DTrilinos_ENABLE_Compadre:BOOL=ON \ Moved Compadre switch from here
```

**Comment by kuberry** [comment]
I'm glad it works now and is documented (for posterity). Thanks @pbosler
